package com.pt.businessLayer;

import com.pt.dataAccessLayer.ProductDAO;
import com.pt.model.Product;
import com.pt.validator.ProductValidator;

import java.util.List;

/**
 * Business Logic Layer class for handling operations related to Products.
 * It encapsulates data validation rules and communicates with the underlying Data Access Object (DAO).
 */

public class ProductBLL {
    private final ProductDAO productDAO = new ProductDAO();
    private final ProductValidator productValidator = new ProductValidator();

    /**
     * Retrieves all products currently registered in the database warehouse.
     *
     * @return a List containing all Product objects
     */
    public List<Product> findAllProducts() {
        return productDAO.findAll();
    }

    /**
     * Filters and retrieves all available products from the database whose stock is strictly greater than zero.
     * Utilizes Java Lambda expressions and Streams for pipeline processing.
     *
     * @return a List of in-stock Product objects
     */
    public List<Product> findAvailableProducts() {
        return productDAO.findAll()
                .stream()
                .filter(product -> product.getStock() > 0)
                .toList();
    }

    /**
     * Retrieves all products sorted alphabetically by their name, ignoring character case.
     * Utilizes Java Streams and a custom sorting comparator.
     *
     * @return a List of alphabetically sorted Product objects
     */
    public List<Product> findProductsSortedByName() {
        return productDAO.findAll()
                .stream()
                .sorted((product1, product2) -> product1.getName().compareToIgnoreCase(product2.getName()))
                .toList();
    }

    /**
     * Finds a specific warehouse product based on its unique primary key identifier.
     *
     * @param id the unique identifier of the product
     * @return the found Product entity object, or null if no record matches the given ID
     */
    public Product findProductById(int id) {
        return productDAO.findById(id);
    }

    /**
     * Validates the integrity of a product instance and inserts it into the database records.
     *
     * @param product the Product model object to be validated and saved
     * @return the autogenerated unique primary key database index assigned to the new product, or -1 if insertion fails
     * @throws IllegalArgumentException if the provided product attributes violate validation constraints
     */
    public int addProduct(Product product) {
        productValidator.validate(product);
        return productDAO.insert(product);
    }

    /**
     * Validates the modifications applied to an existing product and updates its persistent database record.
     *
     * @param product the Product model object containing the updated parameters (must have a valid primary key ID)
     * @throws IllegalArgumentException if the updated attributes fail the validation checks
     */
    public void updateProduct(Product product) {
        productValidator.validate(product);
        productDAO.update(product);
    }

    /**
     * Deletes a product entry from the database using its unique identifier.
     *
     * @param id the unique identifier of the product targeted for deletion
     */
    public void deleteProduct(int id) {
        productDAO.delete(id);
    }
}